### ISSUE TITLE
derridas margins infrastructure

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2485]
- [x] crawl derrida to test resulting size of WARC - RK
- [x] create to vms to crawl (staging and prod) - FK (RK to provide names)
     - cdh-test-derrida-crawl1
     - cdh-test-derrida1
     - cdh-derrida-crawl1
     - cdh-derrida1
- [ ] create to VMS to render warc files (staging and prod) - FK
- [x] create ansible playbook for crawler - RK
- [ ] create ansible playbook for rendering warc files - RK

**Comment by rlskoeser** [comment]
Used [browsertrix-crawler](https://github.com/webrecorder/browsertrix-crawler) to do a test crawl of the derridas margins site from my laptop. It ran for ~ 4 hours (fwiw I was also using the laptop for other things during this time).

Here's how I ran it and the output I got:

```
% docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://derridas-margins.princeton.edu/ --generateWACZ --text --collection derridasmargins-test
Text Extraction: Enabled
Load timeout for https://derridas-margins.princeton.edu/library/husserl-der-ursprung-der-geometrie-als-intentional-historisches-problem-1962-B/gallery/p-220-inside-back-cover-insertion-a-recto/ TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/interventions/?annotation_type=line&page=11 TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/interventions/?annotation_type=marginal+mark&page=30 TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/interventions/?page=16&annotation_type=underlining TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/references/?page=54 TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/interventions/?page=33&annotation_type=line TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/references/?page=33 TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Load timeout for https://derridas-margins.princeton.edu/interventions/?page=51 TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111

== Start:     2021-09-21 16:31:33.659
== Now:       2021-09-21 20:27:55.506 (running for 3.9 hours)
== Progress:  2868 / 2868 (100.00%), errors: 1 (0.03%)
== Remaining: 0.0 ms (@ 0.20 pages/second)
== Sys. load: 37.0% CPU / 79.7% memory
== Workers:   1
   #0 IDLE
Waiting to ensure pending data is written to WARCs...
Generating WACZ
Validating passed pages.jsonl file
Reading and Indexing All WARCs
Writing archives...
Generating page index from passed pages...
Header detected in the passed pages.jsonl file
Generating datapackage.json
Generating datapackage-digest.json
```

Here are the sizes of the `.warc.gz` files that were generated:
```
% ls -l crawls/collections/derridasmargins-test/archive/
total 1657512
-rw-r--r--  1 rkoeser  staff   67718672 Sep 21 16:25 rec-20210921163135141911-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   86732864 Sep 21 16:27 rec-20210921163135316862-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   49708883 Sep 21 16:23 rec-20210921163135356001-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff  103751541 Sep 21 16:25 rec-20210921163135484484-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff  138867254 Sep 21 16:27 rec-20210921163135498226-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff  121607803 Sep 21 16:27 rec-20210921163135546143-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff  145825162 Sep 21 16:27 rec-20210921163135567093-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   59891655 Sep 21 16:19 rec-20210921163136049692-23b1f8eb3af7.warc.gz
```
or same in human readable sizes:
```
% ls -lh crawls/collections/derridasmargins-test/archive/
total 1657512
-rw-r--r--  1 rkoeser  staff    65M Sep 21 16:25 rec-20210921163135141911-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff    83M Sep 21 16:27 rec-20210921163135316862-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff    47M Sep 21 16:23 rec-20210921163135356001-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff    99M Sep 21 16:25 rec-20210921163135484484-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   132M Sep 21 16:27 rec-20210921163135498226-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   116M Sep 21 16:27 rec-20210921163135546143-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff   139M Sep 21 16:27 rec-20210921163135567093-23b1f8eb3af7.warc.gz
-rw-r--r--  1 rkoeser  staff    57M Sep 21 16:19 rec-20210921163136049692-23b1f8eb3af7.warc.gz
```

looks like the entire collection comes to ~ 1.5GB:
```
% du -sh crawls/collections/derridasmargins-test/
1.5G	crawls/collections/derridasmargins-test/
```

but based on this output I think the wacz file may be duplicating the content in the archive warc.gz files:
```
% du -sh crawls/collections/derridasmargins-test/*
809M	crawls/collections/derridasmargins-test/archive
752M	crawls/collections/derridasmargins-test/derridasmargins-test.wacz
  0B	crawls/collections/derridasmargins-test/indexes
7.1M	crawls/collections/derridasmargins-test/pages
  0B	crawls/collections/derridasmargins-test/static
  0B	crawls/collections/derridasmargins-test/templates
```

**Comment by rlskoeser** [comment]
I haven't investigated yet what urls are included or tried to play the archive back with pywb — if this includes IIIF image urls that we'll be able to exclude then the final archive will be smaller. (Although if there's any missing content then vice versa)
