### ISSUE TITLE
libgdal cannot find simpler_tiles static library files for the `geo_works-derivatives`

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#337]
When provisioning the following errors are encountered by Capistrano:

https://gist.github.com/tpendragon/b946424648d331afbab49dd232f21db3

This could not be resolved by reprovisioning the server, and invoking Capistrano locally yielded the same results:

```
LoadError: libgdal.so.1: cannot open shared object file: No such file or directory - /opt/figgy/shared/bundle/ruby/2.4.0/gems/simpler-tiles-0.3.1/lib/simpler_tiles/simpler_tiles.so
 DEBUG [a03ffeed] 	/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/simpler-tiles-0.3.1/lib/simpler_tiles.rb:7:in `<top (required)>'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives/processors/rendering.rb:2:in `<top (required)>'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives/processors.rb:9:in `<module:Processors>'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives/processors.rb:4:in `<module:Derivatives>'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives/processors.rb:3:in `<module:GeoWorks>'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives/processors.rb:2:in `<top (required)>'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives.rb:9:in `<module:Derivatives>'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives.rb:7:in `<module:GeoWorks>'
/opt/figgy/shared/bundle/ruby/2.4.0/bundler/gems/geo_works-derivatives-62a89f482845/lib/geo_works/derivatives.rb:6:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:95:in `rescue in block in require'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/opt/figgy/releases/20180924132806/config/application.rb:12:in `<top (required)>'
/opt/figgy/releases/20180924132806/Rakefile:5:in `require_relative'
/opt/figgy/releases/20180924132806/Rakefile:5:in `<top (required)>'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
 DEBUG [a03ffeed] 	LoadError: cannot load such file -- geo_works-derivatives
```

**Comment by jrgriffiniii** [comment]
This was resolved by @eliotjordan at 11:21 EDT by rebuilding the `simple-tiles` libraries on the server environments for Figgy: https://pulibrary.slack.com/archives/C9ZJGKKJP/p1537802471000100
