### ISSUE TITLE
oawaiver verify fails intermittently

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3657]
The test here: https://github.com/pulibrary/princeton_ansible/blob/e0cfa3d5d01f96c1d8a624abc68983f03206d57c/roles/oawaiver/molecule/default/verify.yml#L50 always passes on local containers, but sometimes fails on CI.

This is a longstanding and very annoying failure.

Currently blocking #3645.

**Comment by kayiwa** [comment]
```
root@instance:/# gem bundler info
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command bundler
	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:204:in `find_command'
	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:249:in `invoke_command'
	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:191:in `process_args'
	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/command_manager.rb:149:in `run'
	/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/gem_runner.rb:51:in `run'
	/usr/local/bin/gem:10:in `<main>'
root@instance:/# gem info bundler

*** LOCAL GEMS ***

bundler (2.4.5, 2.3.11)
    Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
    Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
    Morris, James Wen, Tim Moore, André Medeiros, Jessica Lynn Suttles,
    Terence Lee, Carl Lerche, Yehuda Katz
    Homepage: https://bundler.io
    License: MIT
    Installed at (2.4.5, default): /usr/local/lib/ruby/gems/3.0.0
                 (2.3.11): /usr/local/lib/ruby/gems/3.0.0

    The best way to manage your application's dependencies
    ```
    this is the error inside the container.

**Comment by carolyncole** [comment]
That is exactly the same as on CI:
```
bundler (2.4.5, 2.3.11)
    Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
    Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
    Morris, James Wen, Tim Moore, André Medeiros, Jessica Lynn Suttles,
    Terence Lee, Carl Lerche, Yehuda Katz
    Homepage: https://bundler.io
    License: MIT
    Installed at (2.4.5, default): /usr/local/lib/ruby/gems/3.0.0
                 (2.3.11): /usr/local/lib/ruby/gems/3.0.0

    The best way to manage your application's dependencies
```

**Comment by VickieKarasic** [comment]
Also currently blocking #3662

**Comment by acozine** [comment]
The oawaiver role tests always pass when run by themselves (locally and also in #3661). However, they fail in combination with other roles. Needs more investigation -maybe the test is failing for a reason!

**Comment by acozine** [comment]
The oawaiver role is now failing CI on the main branch, but the failure is an idempotence failure. Not sure if it's related. The test run is here:
https://github.com/pulibrary/princeton_ansible/actions/runs/4198847185/jobs/7283000031 
and the 'changed' tasks include:
```
  TASK [ruby_s : ruby_s | uninstall wrong version of bundler] ********************
  changed: [instance]
  
  TASK [ruby_s : ruby_s | get gem home] ******************************************
  changed: [instance]
  
  TASK [ruby_s : ruby_s | remove installed bundler if default] *******************
  changed: [instance]
  
  TASK [ruby_s : ruby_s | install global bundler, specific version] **************
  changed: [instance]
  
  TASK [ruby_s : ruby_s | install global bundler, any version] *******************
  skipping: [instance]
  
  TASK [ruby_s : ruby_s | update rubygems] ***************************************
  changed: [instance]
  
  TASK [ruby : ruby | install the dependencies] **********************************
  skipping: [instance]
```

**Comment by kayiwa** [comment]
closed by https://github.com/pulibrary/princeton_ansible/pull/3705
