### ISSUE TITLE
jammy jellyfish capistrano transport

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3754]
we are unable to deploy from the slack robots channel to dss-staging 

we are also unable to use the `deploy` user to successfully `deploy` to pas-staging which can authenticate successfully but unsuccessfully using capistrano

```bash
➜ ssh deploy@slavery-staging1.princeton.edu
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-60-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro
Last login: Mon Mar 20 21:23:58 2023 from 172.20.216.34
```

but 

```bash
➜ cap staging deploy
00:00 git:wrapper
      01 mkdir -p /tmp
deploy@slavery-staging1.princeton.edu's password:
deploy@slavery-staging1.princeton.edu's password:
#<Thread:0x000000014b48a228 /Users/kayiwa/.local/share/rtx/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/Users/kayiwa/.local/share/rtx/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@slavery-staging1.princeton.edu: disconnected: Too many authentication failures (2) (SSHKit::Runner::ExecuteError)
	from /Users/kayiwa/.local/share/rtx/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/kayiwa/.local/share/rtx/installs/ruby/3.0.4/lib/ruby/gems/3.0.0/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:198:in `block in poll_message': disconnected: Too many authentication failures (2) (Net::SSH::Disconnect)
```

https://askubuntu.com/questions/1404049/ssh-without-password-does-not-work-after-upgrading-from-18-04-to-22-04

related to  https://github.com/pulibrary/DSS/issues/341

**Comment by maxkadel** [comment]
So, I am able to deploy to pas staging locally without making any changes. I suspect the Princeton and Slavery issue may be different from the DSS issue.

**Comment by kayiwa** [comment]
Deployment is now done by way of Ansible Tower which works.
