### ISSUE TITLE
Rails debugging for Manifold

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#4212]
We are consistently getting a 503 error when following the out-of-the-box installation instructions for [Manifold](https://github.com/ManifoldScholar/manifold).  Manifold is an omnibus solution bundle, meaning it runs its own services including nginx, sidekiq, Rails, cable, logrotate, and others.  The error is happening before manifold even reaches any of PUL's own networking tools or infrastructure.

Determine which service(s) cannot communicate with other services within the solution bundle and troubleshoot for installation.

**Comment by jrgriffiniii** [comment]
While investigating this with @carolyncole and @kayiwa, it was discovered that the client was implemented using the Server-Side React framework along with Redux.

Redux Actions utilize the Fetch API in order to request JSON data from the API endpoints, however, the URL for these endpoints is forced over the HTTP (rather than tunneled over TLS using HTTPS). This is due to the following Chef template:

https://github.com/ManifoldScholar/manifold-omnibus/blob/master/cookbooks/manifold/templates/default/browser-env.js.erb#L5

Manually editing this permits one to ensure that the `SSL_ENABLED` value is set, which is then propagated to the following:

https://github.com/ManifoldScholar/manifold/blob/master/client/src/config/services/index.js#L15

Without adjusting this, setting the Manifold variable `@nginx["listen_https"]` to true will trigger a failure for the NGINX reverse proxy, as one is required to provide a valid X.509 certificate for the NGINX reverse proxy even when this is load-balanced.

**Comment by jrgriffiniii** [comment]
Using a fork under my personal account (https://github.com/jrgriffiniii/manifold), I have made progress with the following pull requests:

- https://github.com/jrgriffiniii/manifold/pull/1
- https://github.com/jrgriffiniii/manifold/pull/2

These support Ruby 3.0.5 releases and integrate Lando for testing.

**Comment by jrgriffiniii** [comment]
Unfortunately, attempting to execute the `rspec` test suites raises the following errors:

```bash
[...]
An error occurred while loading ./spec/services/search/query_builder_spec.rb.
Failure/Error: raise FormattedAttributes::AlreadyDefinedError, "Already defined #{definition.path.inspect}" unless @definitions.add?(definition)

FormattedAttributes::AlreadyDefinedError:
  Already defined "series_title"
# ./app/services/formatted_attributes/configuration.rb:112:in `add!'
# ./app/services/formatted_attributes/configuration.rb:28:in `define!'
# ./app/models/concerns/has_formatted_attributes.rb:66:in `has_formatted_attribute'
```

This seems to be related to the following area of the codebase:

```bash
An error occurred while loading ./spec/services/search/query_builder_spec.rb.
Failure/Error: mapping.fetch(needle, &block)

KeyError:
  key not found: ReadingGroupProject(id: uuid, reading_group_id: uuid, project_...
  Did you mean?  "reading_group"
# ./app/services/concerns/multi_keyable.rb:153:in `block in fetch'
# ./app/services/concerns/multi_keyable.rb:152:in `fetch'
# ./app/models/concerns/collection_entry.rb:48:in `collector_definition'
# ./app/models/concerns/collection_entry.rb:54:in `collectable_definition'
# ./app/models/concerns/collection_entry.rb:27:in `collectable_associations'
# ./app/models/concerns/reading_group_entry.rb:8:in `block in <module:ReadingGroupEntry>'
```

**Comment by jrgriffiniii** [comment]
Until the new release of Manifold is completed (currently https://github.com/ManifoldScholar/manifold/pull/3605 is blocking this), it is been decided that progress on this should be deprioritized.

**Comment by bess** [comment]
We are not going to be running manifold ourselves, so we are closing this ticket.
